---
vm_provider: 'docker'

docker:
  image: 'centos/systemd'

salt:
  salt_path: './salt'
  pillar_path: './pillar'

hosts:
  - 'saltmaster'
#  - 'loadbalancer'
#  - 'web01'
#  - 'web02'
  - 'dbmaster'
  - 'dbslave'
#  - 'monitor'
